
//	MIT License
//
//	Copyright (c) 2017 Matej Artnak
//
//	Permission is hereby granted, free of charge, to any person obtaining a copy
//	of this software and associated documentation files (the "Software"), to deal
//	in the Software without restriction, including without limitation the rights
//	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//	copies of the Software, and to permit persons to whom the Software is
//	furnished to do so, subject to the following conditions:
//
//	The above copyright notice and this permission notice shall be included in all
//	copies or substantial portions of the Software.
//
//	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//	SOFTWARE.
//
//
//
//-----------------------------------
//	ILI9341 Driver library for STM32
//-----------------------------------
//
//	While there are other libraries for ILI9341 they mostly require either interrupts, DMA or both for fast drawing
//	The intent of this library is to offer a simple yet still reasonably fast alternatives for those that
//	do not wish to use interrupts or DMA in their projects.
//
//	Library is written for STM32 HAL library and supports STM32CUBEMX. To use the library with Cube software
//	you need to tick the box that generates peripheral initialization code in their own respective .c and .h file
//
//
//-----------------------------------
//	Performance
//-----------------------------------
//	Settings:	
//	--SPI @ 50MHz 
//	--STM32F746ZG Nucleo board
//	--Redraw entire screen
//
//	++		Theoretical maximum FPS with 50Mhz SPI calculated to be 40.69 FPS
//	++		320*240 = 76800 pixels, each pixel contains 16bit colour information (2x8)
//	++		Theoretical Max FPS: 1/((320*240*16)/50000000)
//
//	With ART Accelerator, instruction prefetch, CPI ICACHE and CPU DCACHE enabled:
//
//	-FPS:									39.62
//	-SPI utilization:			97.37%
//	-MB/Second:						6.09
//
//	With ART Accelerator, instruction prefetch, CPI ICACHE and CPU DCACHE disabled:
//
//	-FPS:									35.45
//	-SPI utilization:			87.12%
//	-MB/Second:						5.44
//	
//	ART Accelerator, instruction prefetch, CPI ICACHE and CPU DCACHE settings found in MXCUBE under "System-> CORTEX M7 button"
//
//
//
//-----------------------------------
//	How to use this library
//-----------------------------------
//  (The following explanations might not be correct.I(Kasim) have changed code to support parallel 8080 communication.)
//	-generate SPI peripheral and 3 GPIO_SPEED_FREQ_VERY_HIGH GPIO outputs
//	 		++Library reinitializes GPIOs and SPIs generated by gpio.c/.h and spi.c/.h using MX_X_Init(); calls
//			++reinitialization will not clash with previous initialization so generated initializations can be laft as they are
//	-If using MCUs other than STM32F7 you will have to change the #include "stm32f7xx_hal.h" in the ILI9341_STM32_Driver.h to your respective .h file
//	-define your HSPI_INSTANCE in ILI9341_STM32_Driver.h
//	-define your CS, DC and RST outputs in ILI9341_STM32_Driver.h
//	-check if ILI9341_SCREEN_HEIGHT and ILI9341_SCREEN_WIDTH match your LCD size
//			++Library was written and tested for 320x240 screen size. Other sizes might have issues**
//	-in your main program initialize LCD with ILI9341_Init();
//	-library is now ready to be used. Driver library has only basic functions, for more advanced functions see ILI9341_GFX library	
//
//-----------------------------------

/* Includes ------------------------------------------------------------------*/
#include "ILI9341_STM32_Driver.h"

#define HSPI_INSTANCE							&hspi5

////CHIP SELECT PIN AND PORT, STANDARD GPIO
#define LCD_CS_PORT								GPIOC
#define LCD_CS_PIN								CS_Pin

////DATA COMMAND PIN AND PORT, STANDARD GPIO
#define LCD_DC_PORT								GPIOC
#define LCD_DC_PIN								DC_Pin

////RESET PIN AND PORT, STANDARD GPIO
#define	LCD_RST_PORT							GPIOC
#define	LCD_RST_PIN								RST_Pin
#define D2_Pin GPIO_PIN_2
#define D2_GPIO_Port GPIOE
#define D3_Pin GPIO_PIN_3
#define D3_GPIO_Port GPIOE
#define D4_Pin GPIO_PIN_4
#define D4_GPIO_Port GPIOE
#define D5_Pin GPIO_PIN_5
#define D5_GPIO_Port GPIOE
#define D6_Pin GPIO_PIN_6
#define D6_GPIO_Port GPIOE
#define D7_Pin GPIO_PIN_7
#define D7_GPIO_Port GPIOE
#define LCD_RST_Pin GPIO_PIN_8
#define LCD_RST_GPIO_Port GPIOE
#define LCD_BCK_PWM_Pin GPIO_PIN_9
#define LCD_BCK_PWM_GPIO_Port GPIOE
#define LCD_RD_Pin GPIO_PIN_10
#define LCD_RD_GPIO_Port GPIOE
#define LCD_WR_Pin GPIO_PIN_11
#define LCD_WR_GPIO_Port GPIOE
#define LCD_RS_Pin GPIO_PIN_12
#define LCD_RS_GPIO_Port GPIOE
#define LCD_CS_Pin GPIO_PIN_15
#define LCD_CS_GPIO_Port GPIOE
#define D0_Pin GPIO_PIN_0
#define D0_GPIO_Port GPIOE
#define D1_Pin GPIO_PIN_1
#define D1_GPIO_Port GPIOE
#define LCD_DATA_PORT		D0_GPIO_Port //Port E

#define RD_ACTIVE		HAL_GPIO_WritePin(LCD_RD_GPIO_Port, LCD_RD_Pin, GPIO_PIN_RESET);
#define RD_IDLE			HAL_GPIO_WritePin(LCD_RD_GPIO_Port, LCD_RD_Pin, GPIO_PIN_SET);
#define WR_ACTIVE		HAL_GPIO_WritePin(LCD_WR_GPIO_Port, LCD_WR_Pin, GPIO_PIN_RESET);
#define WR_IDLE			HAL_GPIO_WritePin(LCD_WR_GPIO_Port, LCD_WR_Pin, GPIO_PIN_SET);
#define CD_COMMAND	HAL_GPIO_WritePin(LCD_RS_GPIO_Port, LCD_RS_Pin, GPIO_PIN_RESET);
#define CD_DATA			HAL_GPIO_WritePin(LCD_RS_GPIO_Port, LCD_RS_Pin, GPIO_PIN_SET);
#define CS_ACTIVE		HAL_GPIO_WritePin(LCD_CS_GPIO_Port, LCD_CS_Pin, GPIO_PIN_RESET);
#define CS_IDLE			HAL_GPIO_WritePin(LCD_CS_GPIO_Port, LCD_CS_Pin, GPIO_PIN_SET);

//#ifndef RD_STROBE
// #define RD_STROBE  {RD_ACTIVE; RD_IDLE;}
//#endif
#define WR_STROBE { WR_ACTIVE; WR_IDLE; }

/* Global Variables ------------------------------------------------------------------*/
volatile uint16_t LCD_HEIGHT = ILI9341_SCREEN_HEIGHT;
volatile uint16_t LCD_WIDTH	 = ILI9341_SCREEN_WIDTH;

/* Initialize SPI */
void ILI9341_Pin_Level_Init(void)
{
	RD_IDLE
	CS_ACTIVE
	CS_IDLE
	WR_IDLE
}

/*Send data (char) to LCD*/
void ILI9341_SPI_Send(unsigned char SPI_Data)
{
//HAL_SPI_Transmit(HSPI_INSTANCE, &SPI_Data, 1, 1);
}

/* Send command (char) to LCD */
void ILI9341_Write_Command(uint8_t Command)
{
		uint32_t large_command = Command;
		CS_ACTIVE
		CD_COMMAND
		LCD_DATA_PORT->BSRR = ( ( (~large_command)<<16) & 0x00FFFFFF ) | (large_command & 0x000000FF); //Set pins to the 8 bit number
		WR_STROBE
		CS_IDLE
}

/* Send Data (char) to LCD */
void ILI9341_Write_Data(uint8_t Data)
{
		uint32_t large_data = Data;
		CS_ACTIVE
		CD_DATA
		LCD_DATA_PORT->BSRR = ( ( (~large_data)<<16) & 0x00FFFFFF ) | (large_data & 0x000000FF); //Set pins to the 8 bit number
		WR_STROBE
		CS_IDLE
}

/* Set Address - Location block - to draw into */
void ILI9341_Set_Address(uint16_t X1, uint16_t Y1, uint16_t X2, uint16_t Y2)
{
	ILI9341_Write_Command(0x2A);
	ILI9341_Write_Data(X1>>8);
	ILI9341_Write_Data(X1);
	ILI9341_Write_Data(X2>>8);
	ILI9341_Write_Data(X2);

	ILI9341_Write_Command(0x2B);
	ILI9341_Write_Data(Y1>>8);
	ILI9341_Write_Data(Y1);
	ILI9341_Write_Data(Y2>>8);
	ILI9341_Write_Data(Y2);

	ILI9341_Write_Command(0x2C);
}

/*HARDWARE RESET*/
void ILI9341_Reset(void)
{
		HAL_GPIO_WritePin(LCD_RST_GPIO_Port, LCD_RST_Pin, GPIO_PIN_SET);
		HAL_Delay(200);
		HAL_GPIO_WritePin(LCD_CS_GPIO_Port, LCD_CS_Pin, GPIO_PIN_RESET);
		HAL_Delay(200);
		HAL_GPIO_WritePin(LCD_RST_GPIO_Port, LCD_RST_Pin, GPIO_PIN_SET);	
}

/*Ser rotation of the screen - changes x0 and y0*/
void ILI9341_Set_Rotation(uint8_t Rotation) 
{
	
uint8_t screen_rotation = Rotation;

ILI9341_Write_Command(0x36);
HAL_Delay(1);
	
switch(screen_rotation) 
	{
		case SCREEN_VERTICAL_1:
			ILI9341_Write_Data(0x40|0x08);
			LCD_WIDTH = 240;
			LCD_HEIGHT = 320;
			break;
		case SCREEN_HORIZONTAL_1:
			ILI9341_Write_Data(0x20|0x08);
			LCD_WIDTH  = 320;
			LCD_HEIGHT = 240;
			break;
		case SCREEN_VERTICAL_2:
			ILI9341_Write_Data(0x80|0x08);
			LCD_WIDTH  = 240;
			LCD_HEIGHT = 320;
			break;
		case SCREEN_HORIZONTAL_2:
			ILI9341_Write_Data(0x40|0x80|0x20|0x08);
			LCD_WIDTH  = 320;
			LCD_HEIGHT = 240;
			break;
		default:
			//EXIT IF SCREEN ROTATION NOT VALID!
			break;
	}
}

/*Enable LCD display*/
void ILI9341_Enable(void)
{
	HAL_GPIO_WritePin(LCD_RST_GPIO_Port, LCD_RST_Pin, GPIO_PIN_SET);
}

/*Initialize LCD display*/
void ILI9341_Init(void)
{

ILI9341_Enable();
ILI9341_Pin_Level_Init();
ILI9341_Reset();

//SOFTWARE RESET
ILI9341_Write_Command(0x01);
HAL_Delay(1000);
/*Those setting values are copied from MikroC example codes for EasyMx Pro v7*/
//POWER CONTROL A
ILI9341_Write_Command(0xCB);
ILI9341_Write_Data(0x39);
ILI9341_Write_Data(0x2C);
ILI9341_Write_Data(0x00);
ILI9341_Write_Data(0x34);
ILI9341_Write_Data(0x02);

//POWER CONTROL B
ILI9341_Write_Command(0xCF);
//ILI9341_Write_Data(0x00);
//ILI9341_Write_Data(0xC1);
//ILI9341_Write_Data(0x30);
ILI9341_Write_Data(0x00);
ILI9341_Write_Data(0x83);
ILI9341_Write_Data(0x30);

//DRIVER TIMING CONTROL A
ILI9341_Write_Command(0xE8);
ILI9341_Write_Data(0x85);
ILI9341_Write_Data(0x01);
ILI9341_Write_Data(0x79);

//DRIVER TIMING CONTROL B
ILI9341_Write_Command(0xEA);
ILI9341_Write_Data(0x00);
ILI9341_Write_Data(0x00);

//POWER ON SEQUENCE CONTROL
ILI9341_Write_Command(0xED);
ILI9341_Write_Data(0x64);
ILI9341_Write_Data(0x03);
ILI9341_Write_Data(0x12);
ILI9341_Write_Data(0x81);

//PUMP RATIO CONTROL
ILI9341_Write_Command(0xF7);
ILI9341_Write_Data(0x20);

//POWER CONTROL,VRH[5:0]
ILI9341_Write_Command(0xC0);
ILI9341_Write_Data(0x26);

//POWER CONTROL,SAP[2:0];BT[3:0]
ILI9341_Write_Command(0xC1);
ILI9341_Write_Data(0x11);

//VCM CONTROL
ILI9341_Write_Command(0xC5);
ILI9341_Write_Data(0x35);
ILI9341_Write_Data(0x3E);

//VCM CONTROL 2
ILI9341_Write_Command(0xC7);
ILI9341_Write_Data(0xBE);

//MEMORY ACCESS CONTROL
ILI9341_Write_Command(0x36);
ILI9341_Write_Data(0x48);//ILI9341_Write_Data(0x48);//Not sure

//PIXEL FORMAT
ILI9341_Write_Command(0x3A);
ILI9341_Write_Data(0x55);

//FRAME RATIO CONTROL, STANDARD RGB COLOR
ILI9341_Write_Command(0xB1);
ILI9341_Write_Data(0x00);
ILI9341_Write_Data(0x1B);

//DISPLAY FUNCTION CONTROL
ILI9341_Write_Command(0xB6);
ILI9341_Write_Data(0x0A);
ILI9341_Write_Data(0x82);
ILI9341_Write_Data(0x27);
ILI9341_Write_Data(0x00);

//3GAMMA FUNCTION DISABLE
ILI9341_Write_Command(0xF2);
ILI9341_Write_Data(0x08);

//GAMMA CURVE SELECTED
ILI9341_Write_Command(0x26);
ILI9341_Write_Data(0x01);

//POSITIVE GAMMA CORRECTION
ILI9341_Write_Command(0xE0);
ILI9341_Write_Data(0x1F);
ILI9341_Write_Data(0x1A);
ILI9341_Write_Data(0x18);
ILI9341_Write_Data(0x0A);
ILI9341_Write_Data(0x0F);
ILI9341_Write_Data(0x06);
ILI9341_Write_Data(0x45);
ILI9341_Write_Data(0x87);
ILI9341_Write_Data(0x32);
ILI9341_Write_Data(0x0A);
ILI9341_Write_Data(0x07);
ILI9341_Write_Data(0x02);
ILI9341_Write_Data(0x07);
ILI9341_Write_Data(0x05);
ILI9341_Write_Data(0x00);

//NEGATIVE GAMMA CORRECTION
ILI9341_Write_Command(0xE1);
ILI9341_Write_Data(0x00);
ILI9341_Write_Data(0x25);
ILI9341_Write_Data(0x27);
ILI9341_Write_Data(0x05);
ILI9341_Write_Data(0x10);
ILI9341_Write_Data(0x09);
ILI9341_Write_Data(0x3A);
ILI9341_Write_Data(0x78);
ILI9341_Write_Data(0x4D);
ILI9341_Write_Data(0x05);
ILI9341_Write_Data(0x18);
ILI9341_Write_Data(0x0D);
ILI9341_Write_Data(0x38);
ILI9341_Write_Data(0x3A);
ILI9341_Write_Data(0x1F);

//EXIT SLEEP
ILI9341_Write_Command(0x11);
HAL_Delay(120);

//TURN ON DISPLAY
ILI9341_Write_Command(0x29);

//STARTING ROTATION
ILI9341_Set_Rotation(SCREEN_HORIZONTAL_1);
}

//INTERNAL FUNCTION OF LIBRARY, USAGE NOT RECOMENDED, USE Draw_Pixel INSTEAD
/*Sends single pixel colour information to LCD*/
void ILI9341_Draw_Colour(uint16_t Colour)
{
	//SENDS COLOUR
	unsigned char TempBuffer[2] = {Colour>>8, Colour};	
	uint32_t large_data;
	CD_DATA
	CS_ACTIVE
	large_data = TempBuffer[1];
	LCD_DATA_PORT->BSRR = ( ( (~large_data)<<16) & 0x00FFFFFF ) | (large_data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE
	large_data = TempBuffer[0];
	LCD_DATA_PORT->BSRR = ( ( (~large_data)<<16) & 0x00FFFFFF ) | (large_data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE
	CS_IDLE
}

//INTERNAL FUNCTION OF LIBRARY
/*Sends block colour information to LCD*/
void ILI9341_Draw_Colour_Burst(uint16_t Colour, uint32_t Size)
{
////SENDS COLOUR
	CD_DATA
	CS_ACTIVE
	uint32_t large_color = Colour;
	uint32_t large_color_high = Colour>>8;
	for(uint32_t j = 0; j < Size*2; j+=2)
	{

		LCD_DATA_PORT->BSRR = ( ( (~large_color_high)<<16) & 0x00FFFFFF ) | (large_color_high & 0x000000FF); //Set pins to the 8 bit number
		WR_STROBE
		LCD_DATA_PORT->BSRR = ( ( (~large_color)<<16) & 0x00FFFFFF ) | (large_color & 0x000000FF); //Set pins to the 8 bit number
		WR_STROBE
	}

	CS_IDLE
}

//FILL THE ENTIRE SCREEN WITH SELECTED COLOUR (either #define-d ones or custom 16bit)
/*Sets address (entire screen) and Sends Height*Width ammount of colour information to LCD*/
void ILI9341_Fill_Screen(uint16_t Colour)
{
	ILI9341_Set_Address(0,0,LCD_WIDTH,LCD_HEIGHT);	
	ILI9341_Draw_Colour_Burst(Colour, LCD_WIDTH*LCD_HEIGHT);	
}

//DRAW PIXEL AT XY POSITION WITH SELECTED COLOUR
//
//Location is dependant on screen orientation. x0 and y0 locations change with orientations.
//Using pixels to draw big simple structures is not recommended as it is really slow
//Try using either rectangles or lines if possible
//
void ILI9341_Draw_Pixel(uint16_t X,uint16_t Y,uint16_t Colour) 
{
if((X >=LCD_WIDTH) || (Y >=LCD_HEIGHT)) return;	//OUT OF BOUNDS!

	uint32_t command = 0x2A;
	uint32_t data = 0x00;	
//ADDRESS
	CS_ACTIVE
	CD_COMMAND
	LCD_DATA_PORT->BSRR = ( ( (~command)<<16) & 0x00FFFFFF ) | (command & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE		
	CS_IDLE
	

////XDATA
//unsigned char Temp_Buffer[4] = {X>>8,X, (X+1)>>8, (X+1)};
	CD_DATA
	CS_ACTIVE
	data = X>>8;
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	data = X;
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	data = (X+1)>>8;
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	data = (X+1);
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	CS_IDLE

////ADDRESS		
	CS_ACTIVE
	command = 0x2B;
	CD_COMMAND
	LCD_DATA_PORT->BSRR = ( ( (~command)<<16) & 0x00FFFFFF ) | (command & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE		
	CS_IDLE
	
////YDATA
	CD_DATA
	CS_ACTIVE
	data = Y>>8;
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	data = Y;
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	data = (Y+1)>>8;
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	data = (Y+1);
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	CS_IDLE
	
////ADDRESS		
	CS_ACTIVE
	command = 0x2C;
	CD_COMMAND
	LCD_DATA_PORT->BSRR = ( ( (~command)<<16) & 0x00FFFFFF ) | (command & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE		
	CS_IDLE
	
////COLOUR	
	CD_DATA
	CS_ACTIVE
	data = Colour>>8;
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE	
	data = Colour;
	LCD_DATA_PORT->BSRR = ( ( (~data)<<16) & 0x00FFFFFF ) | (data & 0x000000FF); //Set pins to the 8 bit number
	WR_STROBE
	CS_IDLE	
}

//DRAW RECTANGLE OF SET SIZE AND HEIGTH AT X and Y POSITION WITH CUSTOM COLOUR
//
//Rectangle is hollow. X and Y positions mark the upper left corner of rectangle
//As with all other draw calls x0 and y0 locations dependant on screen orientation
//

void ILI9341_Draw_Rectangle(uint16_t X, uint16_t Y, uint16_t Width, uint16_t Height, uint16_t Colour)
{
if((X >=LCD_WIDTH) || (Y >=LCD_HEIGHT)) return;
if((X+Width-1)>=LCD_WIDTH)
	{
		Width=LCD_WIDTH-X;
	}
if((Y+Height-1)>=LCD_HEIGHT)
	{
		Height=LCD_HEIGHT-Y;
	}
ILI9341_Set_Address(X, Y, X+Width-1, Y+Height-1);
ILI9341_Draw_Colour_Burst(Colour, Height*Width);
}

//DRAW LINE FROM X,Y LOCATION to X+Width,Y LOCATION
void ILI9341_Draw_Horizontal_Line(uint16_t X, uint16_t Y, uint16_t Width, uint16_t Colour)
{
if((X >=LCD_WIDTH) || (Y >=LCD_HEIGHT)) return;
if((X+Width-1)>=LCD_WIDTH)
	{
		Width=LCD_WIDTH-X;
	}
ILI9341_Set_Address(X, Y, X+Width-1, Y);
ILI9341_Draw_Colour_Burst(Colour, Width);
}

//DRAW LINE FROM X,Y LOCATION to X,Y+Height LOCATION
void ILI9341_Draw_Vertical_Line(uint16_t X, uint16_t Y, uint16_t Height, uint16_t Colour)
{
if((X >=LCD_WIDTH) || (Y >=LCD_HEIGHT)) return;
if((Y+Height-1)>=LCD_HEIGHT)
	{
		Height=LCD_HEIGHT-Y;
	}
ILI9341_Set_Address(X, Y, X, Y+Height-1);
ILI9341_Draw_Colour_Burst(Colour, Height);
}

//max Size is 320*240. Number of 16bits in Data.
void ILI9341_Transmit_Data(uint16_t *Data16, uint32_t NumOfPixels)
{
	////SENDS COLOUR
	CD_DATA
	CS_ACTIVE
	uint32_t large_color;
	uint32_t large_color_high;
	for(uint32_t j = 0; j < NumOfPixels; j++)
	{
		large_color = Data16[j];
		large_color_high = Data16[j]>>8;
		LCD_DATA_PORT->BSRR = ( ( (~large_color_high)<<16) & 0x00FFFFFF ) | (large_color_high & 0x000000FF); //Set pins to the 8 bit number
		WR_STROBE
		LCD_DATA_PORT->BSRR = ( ( (~large_color)<<16) & 0x00FFFFFF ) | (large_color & 0x000000FF); //Set pins to the 8 bit number
		WR_STROBE
	}

	CS_IDLE
}
